# Generated by Django 3.1 on 2020-08-29 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200829_1939'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
